### PR TITLE
Add zoom model

### PR DESCRIPTION
**Pull request by sfentress**
This adds json definitions for the two different models, and allows `OrganelleWrapper` to select between them based on the `currentView` property.

It adds different models handlers depending on the `currentView`.

https://www.pivotaltracker.com/story/show/155415014

### CODE REVIEW

**Comment by ekosmin** [comment]
Different model levels, so exciting! Looks like the deployed version is working, but I can't get this going locally. The cell view doesn't load and I get this error:

```
Uncaught (in promise) TypeError: Cannot create property 'image' on string '<!doctype html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> <meta name="theme-color" content="#000000"> <!-- manifest.json provides metadata used when your web app is added to the homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/ --> <link rel="manifest" href="/manifest.json"> <link rel="shortcut icon" href="/favicon.ico"> <!-- Notice the use of  in the tags above. It will be replaced with the URL of the `public` folder during the build. Only files inside the `public` folder can be referenced from the HTML.
Unlike "/favicon.ico" or "favicon.ico", "/favicon.ico" will work correctly both with client-side routing and a non-root public URL. Learn how to configure a non-root public URL by running `npm run build`. --> <title>React App</title> </head> <body> <noscript> You need to enable JavaScript to run this app. </noscript> <div id="root"></div> <!-- This HTML file is a template. If you open it directly in the browser, you will see an empty page.
You can add webfonts, meta tags, or analytics to this file. The build step will place the bundled scripts into the <body> tag.
To begin the development, run `npm start` or `yarn start`. To create a production bundle, use `npm run build` or `yarn build`. --> <script type="text/javascript" src="/static/js/bundle.js"></script></body> </html>'
    at organelle.js:33183
    at <anonymous>
```

**Comment by ekosmin** [comment]
FWIW, on the deployed version where assays are confirmed with one click (which does seem like an improvement), clearing the assays no longer works.

**Comment by sfentress** [comment]
> clearing the assays no longer works
This is now fixed, thanks.

All those changes (assay tool, pheomelanin) will be in their own PRs, but because they're branched off of this one, I feel like it will complicated the PRs to see all those other commits, would would like to make them one at a time.

Were you able to get building to work?

**Comment by ekosmin** [comment]
Makes sense! I know there were a lot of pieces to work on, I'm happy to look at the other reviews when they're ready.

I'm still getting the same build error, with these actions:

```
git clone https://github.com/concord-consortium/connected-bio.git
cd connected-bio
git checkout add-zoom-model
yarn
yarn start
```

Same behavior if I `npm install && npm start`

**Comment by sfentress** [comment]
D'oh, a missing file not checked in. Fixed now.

And I was thinking "it *must* be on his end, because it deployed fine," forgetting that Travis isn't building the app from what's on git, but instead the deploy task uses the local file system. That's a task I hope to get to by the end of the week.

**Pull request merged**
